# Generated by Django 2.0.1 on 2018-05-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_remove_userfavorite_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '课程机构'), (3, '讲师')], verbose_name='收藏类型'),
        ),
    ]
